### ISSUE TITLE
The minified file size is too large

### ISSUE THREAD

**Issue by rshackleton** [cloudinary/cloudinary-video-player#1]
The video player JS size is 1.4MB minified: https://unpkg.com/cloudinary-video-player@0.0.9/dist/cld-video-player.min.js

This seems excessive. We would love to use this library but can this be reduced? Maybe the library split into modules which can be optionally loaded separately? VideoJS should also be required as a dependency and not bundled.

**Comment by idobarnoam** [comment]
Thanks for the feedback! 
We're currently working on optimizing the player's minified size. That being said, we would like to keep our player as stable as possible. Therefore, currently, Video.js 5 is bundled inside the package. We may decide to change that in the future

**Comment by idobarnoam** [comment]
@rshackleton  I'm closing this thread. 
Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by bummzack** [comment]
It seems like this issue has gotten even worse, the latest release from CDN is ~1.7MB.
Importing `cloudinary-video-player` as a module will result in a bundle of almost 6MB in size (minified!).

Making this more modular should be a high priority, so that only the parts that are effectively needed can be added/imported.
Video.js is ~488KB, so a lot of the extra code seems to come from other sources.

**Comment by roeeba** [comment]
Hi @bummzack. Thanks for pointing this out. Our team is working to resolve that. We'll update here once fixed.

**Comment by rshackleton** [comment]
Depending on how much VideoJS is being relied upon, it would be worth moving away from it, we've seen better results with Plyr.

**Comment by roeeba** [comment]
Hi @rshackleton. Thank you for the suggestion. We'll look into it.

**Comment by roeeba** [comment]
The latest video player version (1.4.3) was released and It now includes a lighter "light" version which is less than 100K (minified).
The release includes other changes which you can read about [here](https://cloudinary.com/documentation/cloudinary_video_player).
