### ISSUE TITLE
Replace dependency from lodash to lodash-es

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary-video-player#120]
Hi Team!

Lodash is HUGE and takes a perfomance hit. Please use lodash-es to use only the specific things you need to use for this project.

You might be using lodash in several of your projects. Please move all over to lodash-es. It's a quick one line-replacement.

Thank you

**Comment by brian-cloudinary** [comment]
Hi @bjornharvold, we're in the process of removing the lodash dependency as a whole. 

This will take some time, but in the future we won't be using the lodash module.
