### ISSUE TITLE
VideoJS api access option

### ISSUE THREAD

**Issue by Admsol** [cloudinary/cloudinary-video-player#127]
There is a problem regarding access to certain videoJS API options,

E.g passing the overrideNative option either by using `videoPlayer.videojs.default` or `videoPlayer.videoJS`(throwing an error) fails using the Cloudinary video player , but works for the native VideoJS  player.

(overrideNative option allows for streaming video players to play smoothly on Android)

```javascript
html5: { 
  hls: { 
    overrideNative: true 
   } 
},
```
It would be also awesome to have an option straight in the Cloudinary player, since playback on certain Android device is choppy for streaming m3u8 files

@cnairi

**Comment by taragano** [comment]
Thank you for reporting about it @Admsol.
Our team is taking a look at it and we'll let you know of any updates.

**Comment by maoznir** [comment]
Hi @Admsol

1. Please see this codepen that demonstrates how to do what you're requesting:
https://codepen.io/nirmaoz/pen/wvaORWj

2. In the latest 1.3.4 version the player will set overrideNative: true by default for non safari/ios:
https://github.com/cloudinary/cloudinary-video-player/releases/tag/v1.3.4

Please let me know if this solves your issue
