### ISSUE TITLE
Forcing a custom base url for sources

### ISSUE THREAD

**Issue by yonbeastie** [cloudinary/cloudinary-video-player#130]
This is either a question about documentation or a feature request :)

Is there a way to force a particular base url when setting the video source? e.g.

```js
videoPlayer.source({ 
  "baseUrl": "mediavine-res.cloudinary.com",
  "publicId": "...", 
  "transformation": { ... } 
})
```

The reason for this is that we have a cloud URL of `mediavine-res.cloudinary.com/...`, but the generated URL for some transformations (DASH/VP9) end up being `cloudinary.com/mediavine/...` resulting in a `403` error.

Furthermore, we have a special case where we make requests to a shield URL that is routed to cloudinary (`video-shield.mediavine.com`), but we're not able to do this with the Cloudinary Player, as far as I can tell.

Is this something that could be done by directly accessing the VideoJS instance? Or would this be a reasonable addition to this library? I'd be happy to make the contribution, but may need some direction about where to look.

Thanks in advance!

**Comment by aditimadan-Cloudinary** [comment]
You can use secure_distribution along with private_cdn=true in the config and that will keep the `mediavine-res.cloudinary.com/.` URL.

```
var cld = cloudinary.Cloudinary.new({
   cloud_name: '<cloud name>',
   secure: true,
   private_cdn: true,
   secure_distribution: 'mediavine-res.cloudinary.com'
 });

```

Please test this out and let me know if you have any further questions.

Thanks,
Aditi

**Comment by yonbeastie** [comment]
fantastic, thank you much, this works great.
