### ISSUE TITLE
Could not reference the original source assets in webpack build

### ISSUE THREAD

**Issue by rshackleton** [cloudinary/cloudinary-video-player#2]
I tried to reference the src/index.js file but could not resolve references as they are not relative paths:

```
import 'styles/main.scss'
import cloudinary from 'cloudinary-core'
import VideoPlayer from 'video-player'
import videojs from 'video.js'
```

This should work if it was written like this:

```
import cloudinary from 'cloudinary-core'
import videojs from 'video.js'
import './styles/main.scss'
import VideoPlayer from './video-player'
```

**Comment by idobarnoam** [comment]
Hi
Please note that there is no need to reference src/index.js directly, but rather the dist/cld-video-player.js which is after the webpack packaging. 
Doing something else may indeed cause issues.

**Comment by MaorGariv** [comment]
Hi @rshackleton 

We're currently working on optimizing the bundle size. A few, near future action items include:
- Non-core player modules (such as dash and hls support which results a larger bundle footprint) will be extracted out so users can selectively add/remove them to the player.
- Better compression and uglification for the entire bundle.

Currently there isn't an immediate solution to minimise the bundle size. Rest assured that we're working on it. We'll, of course, let you know once it's ready and published.
