### ISSUE TITLE
"cloudinary-video-player > expose-loader@0.7.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary-video-player#207]
Hi Team Cloudinary!

Is this going to cause an issue? I've seen it for a while but we are just starting to go through all the warnings and follow up with the different vendors.

Cheers,
Bjorn

**Comment by maoznir** [comment]
Hi @bjornharvold thanks for reporting this issue!
A fix for this was merged and will be part of the next version.
