### ISSUE TITLE
installing cloudinary-video-player npm package fails on Windows

### ISSUE THREAD

**Issue by 01ivr3** [cloudinary/cloudinary-video-player#30]
Running `npm install cloudinary-video-player` in PowerShell on Win 10 is throwing the following error

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloudinary-video-player@1.0.1 postinstall: `cp env.example.js env.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloudinary-video-player@1.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I have [cygwin](cygwin.com/install.html) installed, which adds the `cp` command and typically fixes this common issue with other packages.

Any help greatly appreciated.

**Comment by yakirp** [comment]
Hi @01ivr3 ,

Maybe it could be some permission issue? While trying to copy the file?

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
