### ISSUE TITLE
some m3u8 links doesnt work

### ISSUE THREAD

**Issue by Laurentje** [cloudinary/cloudinary-video-player#340]
most of m3u8 streams work on cloudinary player but there m3u8 links doesnt work that works on other players like jwplayer, videojs. it says "Network request failed". sometimes works sometimes not?

**Comment by Laurentje** [comment]
> Hi @Laurentje,
> 
> Could you please provide some examples that work and others that don't work with our players and do work with other players?
> 
> Thanks, Wissam

[m3u8](https://d3qm7vzp07vxse.cloudfront.net/v1/master/77872db67918a151b697b5fbc23151e5765767dc/cmg_PROD_cmg-tv-10070_fe1f5f6c-cd0b-4993-a4a4-6db66be4f313_LE/in/cmg-wftvtv-hls-v3/live.m3u8) this link works with jwplayer, clappr but not work on cloudinary.

**Comment by Vdeub-cloudinary** [comment]
Hi @Laurentje,
It seems it works when the cache is disabled (Inspect > Network Tab), you can try it out here: https://jsfiddle.net/Vdeub/3njmh609/5/.

When it is not working, we do get a CORS issue. Would you mind making sure that those 2 headers are added:

```
Cache-Control no-cache;
'Access-Control-Allow-Origin' '*';
```

Thanks,
Loic
