### ISSUE TITLE
Replace lodash with  lodash-es

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary-video-player#347]
videojs-ima relies on lodash.

Would be much better if it could rely on lodash-es

https://github.com/googleads/videojs-ima/issues/1041

**Comment by victorli-cloudinary** [comment]
Thank you for bringing this feedback to us - we'll pass the message along to a relevant team member and let you know if there are updates to share.

**Comment by victorli-cloudinary** [comment]
Hi there, our internal team noted that we don't use lodash in the VP and that it is a dependency of a dependency so there's not much we can do on our end for that.

**Comment by bjornharvold** [comment]
Thank you for getting back to me. Correct. It’s not your direct dependency.
I created a ticket in your dependency’s repo to use lodash-es as well.
“Video-ima”


Cheers,
Bjorn

-----------
*Bjorn Harvold*
*E-mail*: ***@***.***
*U.S. Mobile*: +1-917-494-6357
*Google Voice*: +1-917-934-3912
*Skype*: +1-917-720-3351 / bjornharvold
*Thai Mobile*: +66-85151-0325
*Hong Kong*: +852-8198-8406
*Facebook*: bjornharvold
*Twitter*: @bjornharvold
*LinkedIn*: bjornharvold

**Comment by victorli-cloudinary** [comment]
Thanks for the update Bjorn, I'll go ahead and close this here for now.
