### ISSUE TITLE
Deprecations: @babel/polyfill@7.12.1

### ISSUE THREAD

**Issue by bjornharvold** [cloudinary/cloudinary-video-player#348]
warning cloudinary-video-player > @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
warning cloudinary-video-player > @babel/polyfill > core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

**Comment by tamaracloudinary** [comment]
Hi Bjorn, 

Thanks for bringing this to our attention. I opened an internal ticket in this matter. 

Best, 
Tamara

**Comment by tamaracloudinary** [comment]
Hi,
This issue has been resolved, so I'm closing it now.
Thank you!
