### ISSUE TITLE
"Playback cannot continue" error in v1.9.5

### ISSUE THREAD

**Issue by ClarkMitchell** [cloudinary/cloudinary-video-player#376]
Getting the following error after upgrading to v1.9.5

`Playback cannot continue. No available working or supported playlists.`

Possibly related to this issue in video.js https://github.com/videojs/http-streaming/issues/910

**Comment by PixelCook** [comment]
Hey there Clark can you please share with me the specific browser, OS, DASH settings and implementation of your code? Do you have a codepen where you can recreate the issue?

**Comment by ClarkMitchell** [comment]
I've recreated the issue in the following codepen https://codepen.io/clarkmitchell/pen/rNrYVOZ

The error occurs for me on MacOS 12.4 with Chrome Canary 111, Chromium 109, and Firefox 109, but does not occur in Safari 15.5.

**Comment by skalahasti-cloudinary** [comment]
Hi Clark,

Thanks for providing the code. 

First of all, the hls/265 does not work in chrome. At this point, it is only partially supported- https://caniuse.com/?search=265

Can you please change the streaming profile of vp9 from vp9_full_hd to full_hd_vp9? 

Streaming profiles are mentioned in the document here: 
https://cloudinary.com/documentation/adaptive_bitrate_streaming#step_1_select_a_streaming_profile

Hope this helps. Please let me know if you have further questions. 

Best Regards,
Sree

**Comment by ClarkMitchell** [comment]
This worked great, thank you.
