### ISSUE TITLE
npm install cloudinary-video-player

### ISSUE THREAD

**Issue by instantgis** [cloudinary/cloudinary-video-player#558]
I am trying to use this in an Angular 17.1.2 app set for the new ESM build @angular-devkit/build-angular:application.
I import this in a stand alone component:

import cloudinary from 'cloudinary-video-player';

When I try to use it:

  ngOnInit(): void {
    cloudinary.videoPlayer('player', {
      cloudName: 'demo'
   });
  }

I get an error on cloudinary.videoPlayer

 Property 'videoPlayer' does not exist on type 'typeof VideoPlayer'

I go to definition on cloudinary-video-player and I see squiggles on 

import { VideoJsPlayerOptions } from 'video.js';

Module '"video.js"' has no exported member 'VideoJsPlayerOptions'. Did you mean to use 'import VideoJsPlayerOptions from "video.js"' instead?

What am I doing wrong?
Anyone has this working in Angular even if its an earlier version?

I want to use this because of the analytics features. I am using

    "cloudinary-video-player": "^1.10.6",

**Comment by instantgis** [comment]
I tried to make a stackblitz to illustrate the issue and it threw errors as soon as I tried to add 

import cloudinary from 'cloudinary-video-player';

to the boilderplace Angular app 

![image](https://github.com/cloudinary/cloudinary-video-player/assets/57132627/b03668c7-ef27-4161-8263-13d09901bb0c)

**Comment by tamaracloudinary** [comment]
Hi there @instantgis, 
Thank you for bringing this to our attention! We're aware of this issue, it holds a high priority for resolution. 
We will report here once a fix is deployed. 
Thanks again!
Tamara
