### ISSUE TITLE
compass-mixins error

### ISSUE THREAD

**Issue by toklok** [cloudinary/cloudinary-video-player#56]
according to this issue on compass-mixins, this tool is no longer being supported... and it throws a warning for webpack, is there a plan to try and squelch this error?

https://github.com/Igosuki/compass-mixins/issues/109

**Comment by yakirp** [comment]
Hey @toklok,
We plan to fix this issue in one of the coming versions of the video player. 
I will update here.

Thanks!
--Yakir

**Comment by tsi** [comment]
fixed in 1.1.3
